data:
  name: pl
  path: /home/kstn/data/crossdock_2020_TD/crossdocked_v1.1_rmsd1.0_pocket10 #./data/crossdocked_v1.1_rmsd1.0_pocket10
  split: /home/kstn/data/crossdock_2020_TD/crossdocked_pocket10_pose_split.pt #./data/crossdocked_pocket10_pose_split.pt
  x_predictor: /home/kstn/codes/mine/PFM_rl/model_params/x_predictor.pth
  h_predictor: /home/kstn/codes/mine/PFM_rl/model_params/h_predictor.pth
  transform:
    ligand_atom_mode: add_aromatic
    random_rot: False

modelp:
  model_mean_type: C0  # ['noise', 'C0']
  beta_schedule: sigmoid
  beta_start: 1.e-7
  beta_end: 2.e-3
  v_beta_schedule: cosine
  v_beta_s: 0.01
  num_diffusion_timesteps: 1000
  loss_v_weight: 100.
  sample_time_method: symmetric  # ['importance', 'symmetric']

  time_emb_dim: 0 #xiugai pre0  gen1
  time_emb_mode: simple
  center_pos_mode: protein

  #add

  #endadd
  node_indicator: True
  model_type: uni_o2
  num_blocks: 1
  num_layers: 8 #9  8  predict 6  PREDICT9
  hidden_dim: 128
  n_heads: 16
  edge_feat_dim: 4  # edge type feat
  num_r_gaussian: 20
  knn: 24 # !
  num_node_types: 8
  act_fn: relu
  norm: True
  cutoff_mode: knn  # [radius, none]
  ew_net_type: global  # [r, m, none]
  num_x2h: 1
  num_h2x: 1
  r_max: 10.
  x2h_out_fc: False
  sync_twoup: False


model:
  model_mean_type: C0  # ['noise', 'C0']
  beta_schedule: sigmoid
  beta_start: 1.e-7
  beta_end: 2.e-3
  v_beta_schedule: cosine
  v_beta_s: 0.01
  num_diffusion_timesteps: 1000
  loss_v_weight: 100.
  sample_time_method: symmetric  # ['importance', 'symmetric']

  time_emb_dim: 1 #xiugai pre0  gen1
  time_emb_mode: simple
  center_pos_mode: protein

  #add

  #endadd
  node_indicator: True
  model_type: uni_o2_dynamic
  num_blocks: 1
  num_layers: 8 #9  8  predict 6
  hidden_dim: 128
  n_heads: 16
  edge_feat_dim: 4  # edge type feat
  num_r_gaussian: 20
  knn: 32 # !
  num_node_types: 8
  act_fn: relu #relu
  norm: True
  cutoff_mode: knn  # [radius, none]
  ew_net_type: global  # [r, m, none]
  num_x2h: 1
  num_h2x: 1
  r_max: 10.
  x2h_out_fc: False
  sync_twoup: False





train:
  ##add


  ##endadd
  seed: 2024
  batch_size: 16 #16
  batch_size_tokenlizer: 64
  num_workers: 1 # 4
  n_acc_batch: 1
  max_iters: 10000000
  val_freq: 100
  pos_noise_std: 0.1 #0.1 xiugai
  max_grad_norm: 8.0
  bond_loss_weight: 1.0
  #add
  exp_name: en_f
  condition_time: True
  dequantization: argmax_variational
  context_node_nf: 0
  nf: 128 #64
  n_layers: 9
  attention: True
  tanh: True
  actnorm: True
  trace: hutch
  ode_regularization: 1.e-3
  data_augmentation: False
  sigma_pos: 0.1
  sigma_type: 0.2
  nll_weight: 0.01
  ot_type: 'ha'
  #end add
  optimizer:
    type: adam
    lr: 5.e-4 #xiugai
    lr_only_ligand: 5.e-4
    weight_decay: 0
    beta1: 0.95
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.6
    patience: 6 #30 muqianshi 20epoch  10  10
    min_lr: 1.e-6
