model:
  checkpoint:  /home/kstn/codes/mine/PFM_rl/model_params/pfm.pth #protection.pth  best_val

training_yml: /home/kstn/codes/mine/PFM_rl/model_params/training.yml


sample:
  seed: 2024
  num_samples: 100
  num_steps: 1000
  pos_only: False
  center_pos_mode: protein
  sample_num_atoms: prior
